### ISSUE TITLE
Files missing ?

### ISSUE THREAD

**Issue by PacoLinux** [dancrossnyc/multics#1]
In 

multics/ldd/include/

Appears this message:

Sorry, we had to truncate this directory to 1,000 files. 1,505 entries were omitted from the list.

**Comment by dancrossnyc** [comment]
I think you must be referring to the GitHub UI's display functionality? Because if you clone the repository, there are 2,505 files in that directory:

```
: spitfire; pwd
/home/cross/reference/multics/ldd/include
: spitfire; ls | wc -w
    2505
: spitfire;
```
